server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8888 #生成项目的端口号

spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/crowdfunding?useUnicode=true&characterEncoding=UTF-8 #生成项目的jdbc连接
        username: root
        password: 1234
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss